swarm/pss: reorganization of package structure
ethersphere/swarm pull request #100
Opened 2017-06-03 14:45 UTC by nolash

Due to cyclic dependency issues PssClient is now separated from the Pss core functionality package.

2017-06-03 18:11 UTC, lmars commented
Please drop all changes to `node/` and `p2p/*` packages, there is no longer a need for them to reference pss directly since the services will now do this directly in both their initializer and start method (e.g. like [this](https://github.com/ethersphere/go-ethereum/blob/network-testing-framework-internode-rpc/swarm/pss/simulations/service_test.go#L139-L147) and [this](https://github.com/ethersphere/go-ethereum/blob/network-testing-framework-internode-rpc/swarm/pss/simulations/service_test.go#L174-L180)).

This then raises the question whether this re-organization is even necessary?

2017-06-05 09:06 UTC, zelig requested changes

2017-06-05 09:06 UTC, zelig commented on swarm/pss/client/client_test.go
> +	<-client.ctx.Done()
same as in incoming

2017-06-05 17:05 UTC, nolash commented on swarm/pss/api/pssapi.go
> +func (pssapi *PssAPI) SendRaw(topic pss.PssTopic, msg pss.PssAPIMsg) error {
actually no, cos it mysteriously collides with PssAPI.Pss.Send if we do that. I suggest SendPss

2017-06-05 17:06 UTC, nolash commented on swarm/pss/api/pssapi.go
> +func (pssapi *PssAPI) NewMsg(ctx context.Context, topic pss.PssTopic) (*rpc.Subscription, error) {
If SendPss (see below) then ReceivePss instead?

2017-06-05 17:23 UTC, lmars commented
Given all of the types are in the `pss` package, I think we should drop the `Pss` prefix from everything, so it would be `pss.API`, `pss.Msg` and `pss.Topic` rather than `pss.PssAPI`, `pss.PssMsg` and `pss.PssTopic`.

2017-06-06 21:25 UTC, closed without merging