swarm/network, swarm/pss, p2p/simulations: adapt test kademlia params
ethersphere/swarm pull request #1022
Opened 2018-11-28 13:44 UTC by justelad

This PR addresses an incorrect node setup on certain simulations, in which the `Reachable` function in the Kademlia was not called at all. This resulted in tests flaking due to peer dialups not being sanctioned correctly.

Similar tests that use `ServiceContext` on setup have been amended to correctly reference the correct `Reachable` function pointer from the `ServiceContext`.

2018-11-28 14:07 UTC, zelig commented
https://travis-ci.org/ethersphere/go-ethereum/jobs/460778170#L2257

2018-11-29 21:15 UTC, zelig requested changes

2018-11-29 21:15 UTC, zelig commented
otherwise LGTM

2018-11-30 01:18 UTC, justelad commented
@zelig that did it. now, I understand that conceptually this if statement should be in the discovery test (i had a weird feeling seeing it there in the first place). what I don't get is why it was failing.

2018-11-30 05:20 UTC, zelig commented
@justelad should 'unskipping' those simulation tests that use `waitTillHealthy` not be part of this PR?

2018-12-03 12:52 UTC, nolash requested changes

2018-12-03 12:52 UTC, nolash commented on p2p/simulations/network.go
> +	conn.wasInitiated = false
Why is it now correct to "allow" disconnection of a disconnected node?

2018-12-03 12:52 UTC, nolash commented on p2p/simulations/network.go
> +				t := time.Duration(time.Duration(r.Intn(200)) * time.Millisecond)
I read this as skewing of time offsets in case nodes try to connect simultaneously? Is this actually a solution to the problem?

2018-12-03 12:52 UTC, nolash commented on swarm/network/hive.go
> +			time.Sleep(timeToSleep * time.Millisecond)
Should this be a parameter not literal `200`?

2018-12-03 12:52 UTC, nolash commented on swarm/network/kademlia.go
> +			t := time.Duration(time.Duration(r.Intn(400)) * time.Millisecond)
Not sure about all these literals, amigo...

2018-12-11 13:32 UTC, closed without merging