swarm/pot: pot.remove fixed
ethersphere/swarm pull request #1098
Opened 2019-01-09 06:53 UTC by gluk256

- bugfix for pot.remove() function
- new tests for pot.remove()
- fixed the comments

2019-01-09 07:08 UTC, zelig approved these changes

2019-01-09 12:25 UTC, nolash requested changes
The bug itself is easy enough to understand. At least in my view, no further explanation of it needed.

However, it would be helpful if you would comment on why you have written the tests you have, and exactly what sets them apart.

Good catch, by the way.

2019-01-09 12:46 UTC, gluk256 commented on swarm/pot/pot.go
>  	r = &Pot{
because the function is recursive, so if not found at the current level of pot tree, it might be be found deeper.

2019-01-09 13:06 UTC, gluk256 commented on swarm/pot/pot_test.go
> +	exp = "[3 2 1 0 0]"
po is calculated in relation to the parent node in the pot

2019-01-09 13:07 UTC, gluk256 commented on swarm/pot/pot_test.go
> +	exp := "[1 2 3 5 0]"
this is how this test function indexes() works. otherwise it's irrelevant.

2019-01-09 13:07 UTC, gluk256 commented on swarm/pot/pot_test.go
> +	exp = "[0 1 2 4 0]"
the root

2019-01-10 10:35 UTC, nolash commented on swarm/pot/pot.go
>  	r = &Pot{
But if not found the contents of the newly created Pot object is identical to the one passed, no? Is the intention that the Pot object that is passed to this (and similar) functions is discarded (only use the returned Pot)?

2019-01-10 10:36 UTC, nolash commented on swarm/pot/pot_test.go
> +	exp = "[3 2 1 0 0]"
Your answer doesn't clear up my questions, I'm afraid.

What is "parent node." Is it the same as the pin?

2019-01-10 10:37 UTC, nolash commented on swarm/pot/pot_test.go
> +	exp := "[1 2 3 5 0]"
Can you elaborate, please? Are you saying that the order doesn't matter? Why doesn't the order matter?

2019-01-10 10:37 UTC, nolash commented on swarm/pot/pot_test.go
> +	exp = "[0 1 2 4 0]"
So we have "root," "parent node," and "pin." Are they the same thing? Please let's use _one_ term.

2019-01-10 19:13 UTC, nolash approved these changes
Cleared up pending comments on call, and attempting a summary of additional questions that arise from this PR, which are out of scope for it (which is why I approve it):

The unexpected `po` results in the tests arise from the fact that in the case of a _hierarchical_ Pot (`TestRemoveSameBin`) the `po` values reported are distances between the added elements, whereas the _flat_  Pot (`TestRemoveDifferentBins`) the `po` values are the distances between the added elements and the _pinned_ value. It's not currently clear whether this is a feature or bug.

Also, the `po` value of the _pinned_ value is 0 because it's explicitly set to this. This value has no meaning for the _pinned_ address, since the `Pot` is hierarchical, and the _pinned_ value, representing the root of the hierarchy, has nothing to compare its `po` to. However, this `po` is also included in the result arrays in the test, which is nonsensical at best (`po` for _pinned_  value has no meaning) to inconsequential at worst (`po` is sometimes in relation to _pinned_ value, sometimes not, and in the former case the value should be `256` instead).

----

Furthermore, there is a confusion of terms involved with the "root" of the `Pot` - variations include:

* pin
* root
* root pin
* pinned item from root
* parent node

it's unclear whether or not all these terms refer to the same thing. The nomenclature needs to be clear and unambiguous.

----

Lastly: The functions in `pot` _really_ should be commented properly (e.g. `add`), and understanding what they do is very difficult.

2019-01-11 19:57 UTC, zelig commented
merged as https://github.com/ethereum/go-ethereum/pull/18431

2019-01-11 19:57 UTC, closed without merging