swarm/network: discovery test health check fix and temp debug code
ethersphere/swarm pull request #116
Opened 2017-08-02 09:02 UTC by zelig

2017-08-04 09:22 UTC, nolash requested changes

2017-08-04 09:22 UTC, nolash commented on swarm/network/kademlia.go
> +func (k *Kademlia) notify(p OverlayConn) {
Could you please leave a comment on what this method actually does?

2017-08-04 09:22 UTC, nolash commented on swarm/network/kademlia.go
> -	k.lock.RLock()
Why do the iterators have the `base []byte` param? If the base isn't kademlia base, should't merely the iterator from `pot/pot.go` be called directly?

2017-08-04 09:22 UTC, nolash commented on swarm/network/kademlia.go
> +type PeerPot struct {
would it be an idea to move testing code like this to separate files and/or have a naming scheme for them (prefix or suffix Tmp for example) so it's easier to weed them out later, and avoid that people start using them if they linger?

2017-08-04 09:22 UTC, nolash commented on swarm/network/kademlia.go
> +	prev := 0
this is also debug code?

2017-08-04 09:22 UTC, nolash commented on swarm/network/kademlia.go
> +	pm := make(map[string]bool)
and this also debug code?

2017-08-04 09:22 UTC, nolash commented on swarm/network/kademlia.go
> +func (k *Kademlia) Healthy(pp *PeerPot) bool {
Here the Healthy method takes a struct labelled for testing only. Is this correct dependency?

2017-08-11 06:56 UTC, zelig commented on swarm/network/kademlia.go
> +	HealthCheck    bool // whether kademlia On should signal completion
exact health can only be calculated if you know all the peers so this is only for tests

2017-08-11 06:57 UTC, zelig commented on swarm/network/kademlia.go
> -	k.lock.RLock()
look at the pss forwarder ;)

2017-08-11 06:59 UTC, zelig commented on swarm/network/kademlia.go
> +type PeerPot struct {
yes this should be in testing code but since its used by the discovery test external to this pkg it would have to be in swarm/network/testing

2017-08-11 07:00 UTC, zelig commented on swarm/network/kademlia.go
> +	prev := 0
not debug, but testing code needed for health check

2017-08-11 07:00 UTC, zelig commented on swarm/network/kademlia.go
> +	pm := make(map[string]bool)
testing code

2017-08-11 07:01 UTC, zelig commented on swarm/network/kademlia.go
> +func (k *Kademlia) Healthy(pp *PeerPot) bool {
the healthy method itself is for testing only since it requires all peers to be known or more precisely 
all actual nearest neighbours of the peer

2017-08-17 16:01 UTC, nolash commented on swarm/network/kademlia.go
> +type PeerPot struct {
but we don't do that now?

2017-08-17 16:07 UTC, nolash approved these changes

2017-09-19 10:15 UTC, zelig commented
obsoleted by #120

2017-09-19 10:15 UTC, closed without merging