swarm/pss: refactoring
ethersphere/swarm pull request #1222
Opened 2019-02-14 15:56 UTC by gluk256

split pss and keystore.
keystore-related code moved to a separate file.

fixes https://github.com/ethersphere/go-ethereum/issues/1214

2019-02-14 18:15 UTC, nolash requested changes
Is all of the code in `keystore.go` copy from `pss.go` or has it been changed? Is it possible to indicate where changes have been made if not, please?

2019-02-14 18:15 UTC, nolash commented on swarm/pss/keystore.go
> +func newKeyStore() *KeyStore {
this should probably be `loadKeyStore()` since we plan to be able to keep it across sessions. And it should probably take filename.

2019-02-14 18:15 UTC, nolash commented on swarm/pss/pss.go
>  func (p *Pss) GenerateSymmetricKey(topic Topic, address PssAddress, addToCache bool) (string, error) {
Shouldn't this method also be in keystore?

2019-02-14 18:15 UTC, nolash commented on swarm/pss/pss.go
>  func (p *Pss) setSymmetricKey(key []byte, topic Topic, address PssAddress, addtocache bool, protected bool) (string, error) {
Shouldn't this also in keystore?

2019-02-14 18:15 UTC, nolash commented on swarm/pss/pss.go
>  func (p *Pss) GetSymmetricKey(symkeyid string) ([]byte, error) {
And this in keystore?

2019-02-14 18:15 UTC, nolash commented on swarm/pss/pss.go
> +	return p.processSymMsg(p.w, envelope)
Shouldnt we get the key from the store instead and decrypt?

2019-02-15 08:35 UTC, nolash requested changes
Please delint https://travis-ci.org/ethersphere/go-ethereum/jobs/493631443

2019-02-15 09:13 UTC, nolash approved these changes

2019-02-16 06:55 UTC, zelig approved these changes

2019-02-17 05:33 UTC, closed without merging