Fix possible localstore test deadlock
ethersphere/swarm pull request #1253
Opened 2019-02-21 11:27 UTC by janos

This PR addresses the issue with sending error to an errChan while inside a mutex lock in readPullSubscriptionBin test function. This PR does not address why that error happened since this errors are reproducible only on travis with race detector. Additionally, this PR includes closing of localstore DB in one test and one benchmark that was missed earlier.

fixes: https://github.com/ethersphere/go-ethereum/issues/1245

2019-02-21 12:24 UTC, frncmx requested changes
I see where the deadlock could have happen. That's fixed. :+1: 

I think we don't deadlock now, but we might leak some goroutines on context timeout.
Let's assume `readPullSubscriptionBin()` is blocked on `errChan <- err` and `checkErrChan()` just calls `t.Fatal()`. What do you think?

2019-02-21 12:28 UTC, janos commented
> Let's assume `readPullSubscriptionBin()` is blocked on `errChan <- err` and `checkErrChan()` just calls `t.Fatal()`. What do you think?

Yes, you are right, leak in test can happen on fatal. I will add select case with context. 👍

2019-02-21 12:55 UTC, frncmx approved these changes

2019-02-21 13:43 UTC, janos commented
This test fixes the deadlock, but the root cause for the error on Travis still needs to be solved.

2019-02-21 17:43 UTC, janos commented
This tests are now passing on Travis with race detector.

The problematic code was locking slices and maps for validating agains data returned by the subscription channel. It was possible that the subscription returned the chunk before the validation slice is updated (concurrently), so a false error was returned as an unexpected chunk. This was solved with including the localstore chunk put into the mutex scope.

Additional improvement is to wait fo gc and gcSizeWrite workers before Close method returns. This is required but missed as this two goroutines may use leveldb after the CLose method returns having the leveldb closed.

2019-02-22 06:17 UTC, zelig approved these changes

2019-02-22 12:03 UTC, frncmx approved these changes
lgtm :+1: 

Just wondering about the 10s timeout. How long is that? As the default grace period on Kuberenetes and Heroku is 30s after sending SIGTERM, then a SIGKILL is sent.
On bare Docker the default timeout is 10s. I guess we are fine with 10s, or could we set it lower?

2019-02-22 12:09 UTC, janos commented
@frncmx 10s appeared to me as long enough for user to wait for swarm shutdown. Maybe 5s would be even better?

2019-02-22 12:17 UTC, frncmx commented
I know we use Kubernetes. I'm not sure what other systems we might run on. 
If 10s is just an arbitrary wait time, maybe I would try to go with 5s 1st as that lowers our chances of getting a SIGKILL from the runtime.

2019-02-22 12:17 UTC, frncmx commented
But I'm not highly opinionated about this.

2019-02-22 12:21 UTC, janos commented
@frncmx I agree, 5s just fine. Thanks.

2019-02-22 12:24 UTC, frncmx approved these changes
thanks; lgtm

2019-02-22 12:35 UTC, janos commented
Thanks for reviews, submitted upstream https://github.com/ethereum/go-ethereum/pull/19153.

2019-02-22 12:35 UTC, closed without merging