cmd/swarm: new localstore database migration
ethersphere/swarm pull request #1297
Opened 2019-03-13 15:12 UTC by justelad

2019-03-20 06:27 UTC, zelig requested changes

2019-03-20 06:27 UTC, zelig commented on swarm/storage/localstore/schema.go
> +const CurrentDbSchema = DbSchemaHalloween
should be sanctuary?

2019-03-20 06:27 UTC, zelig commented on swarm/swarm.go
> +		return nil, errors.New("Legacy database format detected!")
we need more instructions here

2019-03-20 06:27 UTC, zelig commented on cmd/swarm/testdata/datastore_fixture.go
> +package testdata
could this be shorter?

2019-03-20 06:27 UTC, zelig commented on cmd/swarm/flags.go
> +	SwarmLegacyFlag = cli.BoolFlag{
this needs more documemtation

2019-03-22 04:20 UTC, zelig approved these changes

2019-03-28 13:47 UTC, justelad commented
@nonsense I have the results for a dry run migration on my local machine. I'm running an `i5` CPU and my SSD is a SATA III SSD, so performance is not so high.
Datastore size was at around 5.5gb.
I added a [resource pooling](https://github.com/ethersphere/go-ethereum/pull/1297/commits/33e1bb277f193c34e68cb93091762ab59385f85d) to throttle the `db.Put`s. I tried 100 and 200 for pool size without a big difference, so I'm pushing 100 at the moment.
tl;dr: export takes 1 minute for 5 gigs, import takes about 15m
```
export
time ./swarm_mig db export /home/growlster/migrationTest/sw/swarm/bzz-9fae04300e275782afafb52f8a988e23d98b85d9/chunks /home/growlster/migrationTest/exphttps://github.com/ethersphere/go-ethereum/pull/1297/commits/33e1bb277f193c34e68cb93091762ab59385f85dort.tar bd83051b5639cadaba5821a57efa131304a2465b522c19d45e5087eece9dc321                                                                                    
INFO [03-28|21:45:56.713] successfully exported 1375147 chunks 
./swarm_mig db export  /home/growlster/migrationTest/export.tar   24.01s user 19.84s system 78% cpu 56.153 total

import (token pool @ 100)
time ./swarm_mig db import /home/growlster/migrationTest/sw/swarm/bzz-9fae04300e275782afafb52f8a988e23d98b85d9/chunks /home/growlster/migrationTest/export.tar bd83051b5639cadaba5821a57efa131304a2465b522c19d45e5087eece9dc321
INFO [03-28|22:08:13.592] successfully imported 1375147 chunks 
./swarm_mig db import  /home/growlster/migrationTest/export.tar   1134.67s user 131.82s system 164% cpu 12:50.79 total

import (token pool @ 200)
time ./swarm_mig db import /home/growlster/migrationTest/sw/swarm/bzz-9fae04300e275782afafb52f8a988e23d98b85d9/chunks /home/growlster/migrationTest/export.tar bd83051b5639cadaba5821a57efa131304a2465b522c19d45e5087eece9dc321
INFO [03-28|22:29:11.723] successfully imported 1375147 chunks 
./swarm_mig db import  /home/growlster/migrationTest/export.tar   1134.91s user 132.98s system 165% cpu 12:47.45 total
```

2019-04-10 14:47 UTC, merged