submitChequeBeneficiary check
ethersphere/swarm pull request #1565
Opened 2019-07-12 14:10 UTC by Eknir

We make the functionality of submitChequeBeneficiary to return a txHash and two channels on which we can listen to a receipt and error. 
This pattern is in line with [web3 PromiEvents](https://web3js.readthedocs.io/en/1.0/callbacks-promises-events.html).

I am aware that there are no tests yet. If possible, I woud like to have help with this.

2019-07-12 14:38 UTC, mortelli commented on swap/peer.go
> +			log.Error("Got error when calling submitChequeBeneficiary: ", err)
In this case, `err` should be the return value of the function.

2019-07-13 07:06 UTC, vojtechsimetka commented on contracts/swap/swap.go
> +func (s *Swap) InstanceAt(address common.Address, backend bind.ContractBackend) error {
isn't this part of a different PR?

2019-07-13 07:14 UTC, ralph-pichler requested changes

2019-07-13 07:14 UTC, ralph-pichler commented on contracts/swap/swap.go
> +		errorCh <- err
if `err != nil` the following go routine should never be executed

2019-07-13 07:14 UTC, ralph-pichler commented on contracts/swap/swap.go
> +	tx, err := s.Instance.SubmitChequeBeneficiary(auth, serial, amount, timeout, ownerSig)
Should probably already happen in a go routine

2019-07-13 07:14 UTC, ralph-pichler commented on contracts/swap/swap.go
> +	s.Instance, err = contract.NewSimpleSwap(address, backend)
Ok for now but we should really rethink this

2019-07-13 07:14 UTC, ralph-pichler commented on swap/peer.go
> +		log.Info("Could not get an instance of simpleSwap")
should be `log.Error`

2019-07-13 07:14 UTC, ralph-pichler commented on swap/peer.go
> +	tx, receipt, err := otherSwap.SubmitChequeBeneficiary(opts, sp.backend, big.NewInt(int64(cheque.Serial)), big.NewInt(int64(cheque.Amount)), big.NewInt(int64(cheque.Timeout)), cheque.Sig)
make it explicit that receipt and err are channels

2019-07-13 07:14 UTC, ralph-pichler commented on contracts/swap/swap.go
> +		errorCh <- err
should not be sent to channel if nil

2019-07-13 10:00 UTC, ralph-pichler approved these changes
LGTM now

2019-07-13 10:17 UTC, merged