Swap query cheques
ethersphere/swarm pull request #1842
Opened 2019-09-30 19:16 UTC by mortelli

WIP

2019-10-01 20:11 UTC, zelig approved these changes
exemplary PR.

2019-10-01 21:46 UTC, ralph-pichler requested changes
The `TestReceivedCheque` and `TestSentCheque` tests seem overly complex considering what they are supposed to verify. We already have tests that check that if a cheque is sent the correct fields are updated (e.g. the test this was copied from). Instead of actually sending cheques you could just use the setter function on peer or the save functions on swap similar to how you are already doing it in the `TestAllCheques` function.

Also I don't think you're testing the code path for non-added peers. For that you should call the `swap.save*` functions directly (see `TestPeerBalance` for reference).

2019-10-02 10:13 UTC, Eknir approved these changes
Looks good to me!

2019-10-02 15:10 UTC, holisticode approved these changes

2019-10-02 15:41 UTC, mortelli commented
> The `TestReceivedCheque` and `TestSentCheque` tests seem overly complex considering what they are supposed to verify. We already have tests that check that if a cheque is sent the correct fields are updated (e.g. the test this was copied from). Instead of actually sending cheques you could just use the setter function on peer or the save functions on swap similar to how you are already doing it in the `TestAllCheques` function.
> 
> Also I don't think you're testing the code path for non-added peers. For that you should call the `swap.save*` functions directly (see `TestPeerBalance` for reference).

agree completely.

@santicomp2014 and i have addressed these changes, and re-written both of these tests.

thank you for pointing this out, as these new tests allowed us to squash a bug when retrieving cheques from the store for the RPC call.

2019-10-02 16:32 UTC, ralph-pichler requested changes
The `TestAllCheques` test is still missing cheques from disconnected peers. Here it's even more important than in the other tests because the logic for them is a lot more complex.

2019-10-02 16:43 UTC, mortelli commented
thanks @ralph-pichler, addressed.

2019-10-02 16:50 UTC, ralph-pichler approved these changes
LGTM

2019-10-02 19:04 UTC, merged