swarm, swarm/storage: use MultiResolver for resource ownerValidator
ethersphere/swarm pull request #558
Opened 2018-05-18 14:38 UTC by janos

This PR:

- replaces ensClient and ethClient resourcehandler fields with headerGetter and ownerValidator interfaces
- uses MultiResolver for both headerGetter and ownerValidator fields to fix https://github.com/ethersphere/go-ethereum/issues/556
- updates tests to reflect this changes

2018-05-19 00:43 UTC, zelig approved these changes

2018-05-23 06:36 UTC, nolash requested changes
A test fails locally for me:

```
$ go test -v -cpu 4 ./swarm/api/http/
# github.com/ethereum/go-ethereum/swarm/testutil
swarm/testutil/http.go:72:12: unknown field 'EthClient' in struct literal of type "github.com/ethereum/go-ethereum/swarm/storage".ResourceHandlerParams
FAIL	github.com/ethereum/go-ethereum/swarm/api/http [build failed]
```

2018-05-23 09:26 UTC, zelig commented
actually @nolash could you fix this by any chance? or we should wait for @janos ?

2018-05-23 11:29 UTC, nolash commented
Sure it's a minute detail. I'll fix it tday.

2018-05-23 17:46 UTC, nolash approved these changes

2018-05-24 10:35 UTC, merged