Mobile PSS hack with Websocket
ethersphere/swarm pull request #702
Opened 2018-06-11 10:44 UTC by agazso

This branch was originally created as a hack to work on mobile devices with enabling PSS over Websocket/RPC. We managed to get it compile and work on android and iOS.

2018-06-11 12:26 UTC, gbalint requested changes

2018-06-11 14:40 UTC, nonsense commented on vendor/gopkg.in/olebedev/go-duktape.v3/duk_minimal_printf.c
> +#ifndef SIZE_MAX
If you upgrade vendored libraries, please use `govendor` so that the hash in `vendor.json` also gets updated.

2018-06-11 15:38 UTC, agazso commented on mobile/geth.go
> +			//ks := rawStack.AccountManager().Backends(keystore.KeyStoreType)[0].(*keystore.KeyStore)
Fixed

2018-06-11 15:38 UTC, agazso commented on mobile/geth.go
> +			log.Warn("keystore", "ks", ks)
Changed to Debug

2018-06-11 15:38 UTC, agazso commented on mobile/geth.go
> +				//a, err = ks.Find(accounts.Account{Address: common.HexToAddress(config.PssAccount)})
Removed

2018-06-11 15:38 UTC, agazso commented on mobile/geth.go
> +			}
Removed commented code

2018-06-11 15:39 UTC, agazso commented on swarm/swarm.go
> +		})
Removed example code

2018-06-11 15:40 UTC, agazso commented on mobile/geth.go
> +func NewNode(datadir string, config *NodeConfig, ks *keystore.KeyStore) (stack *Node, _ error) {
`ks` is used in the function later, look for the line `if config.PssEnabled && ks != nil {`

2018-06-11 18:15 UTC, zelig commented
could you please put in the description what you needed to achieve this?

and please comment the code.

2018-06-11 18:15 UTC, zelig requested changes

2018-06-11 18:15 UTC, zelig commented on mobile/geth.go
> +				return nil, fmt.Errorf("Can't find swarm account key %s", config.PssAccount)
just set the `err` here too lik eon lne 232, and only return on 238

2018-06-11 18:15 UTC, zelig commented on mobile/geth.go
> +				log.Error("swarm svc", "err", err)
? are you happy continuing even if swarm is not working? not sure i get it
if not return with error right away

2018-06-11 18:15 UTC, zelig commented on mobile/geth.go
> +		bzzSvc := func(ctx *node.ServiceContext) (node.Service, error) {
call this `bzzServiceFunc`

2018-06-11 18:15 UTC, zelig commented on mobile/geth.go
> +			var a accounts.Account
can you explain why all this juggling is needed . Is this not taken care of by the `swarm.New` call?

2018-06-11 18:15 UTC, zelig commented on mobile/geth.go
> +func (n *Node) AddPeer(enode string) error {
you create an rpc client for every `AddPeer` call?
not sure what you are trying to do here, comments would help, in fact for exported methods linter will fail if you write no comment

2018-06-11 18:15 UTC, zelig commented on mobile/pss.go
> +package geth
why is this needed? These APIs already exist

2018-06-12 10:50 UTC, vujevits commented on mobile/geth.go
> +		bzzSvc := func(ctx *node.ServiceContext) (node.Service, error) {
fixed

2018-06-18 10:16 UTC, nolash requested changes
To be perfectly honest, I'm not sure how comfortable I am introducing this hack into the codebase. Pss functionality for light clients should be in fact part of the actual (and properly thought out) light client implementation.

2018-06-18 10:16 UTC, nolash commented on mobile/geth.go
> +			if common.IsHexAddress(config.PssAccount) {
This is not a safe way to access accounts. It should be done explicitly using address.

2018-06-18 10:16 UTC, nolash commented on mobile/geth_test.go
> +	time.Sleep(time.Second * 10)
Test doesn't seem complete. Sleep, then what?

2018-09-28 14:28 UTC, closed without merging