swarm/pss: Message handler refactor
ethersphere/swarm pull request #965
Opened 2018-10-18 08:04 UTC by nolash

This is the first in a series of PR providing the following enhancements to PSS:

## Send fully addressed messages to neighbourhoods

The possibility of sending a message will full `PssAddress` to a neighbourhood of nodes, by interactive with the Kademlia. The primary use case is chunk syncing, where the chunk will have full address but it is d

## Mitigate external influence of resource expenditure

If receiving raw messages, currently all raw messages will be passed on to handling code, effectively passing the responsibility of limiting resource expenditure to the handlers. This can be risky, in case of implementations that do not protect against request flooding. **Whether to handle raw messages or not should therefore be explicitly set on the handler**.

This also pertains to symmetric decryptions, were all registered symmetric keys (for decryption) share the same LRU cache which is tried sequentially on the decrypt. **Instead, there should be symkey decrypt caches per topic.** 

## Symkey filter in message type

To reduce resource expenditure in symmetric decryption, an extra field in the message type will be introduced where up to 32 bytes of symmetric key hint can be added. The hint is a hash of the symmetric key, indexed on both sides. The symkey cache must be refactored to be able to take advantage of this hint. A zero-value in this field would indicate public key crypto.

This also clears the way for upgrading whisper support to v6, as one of the changes in whisper v6 is omission of the symkey nonce in the whisper envelope; with this field it's still possible to identify incoming symmetrically encrypted messages, to avoid a forced attempt of asymmetric decryption on every reception.

# Part 1 

[ ] - Change Handler from func to struct with necessary params
[ ] - Set raw message allowance per handler
[ ] - Add possible recipient logic to use kademlia depth

2018-10-19 15:54 UTC, zelig commented
https://travis-ci.org/ethersphere/go-ethereum/jobs/443683817#L439
pss/notify tests fail @nolash

2018-10-20 11:45 UTC, nolash commented on swarm/network/kademlia.go
> +const (
At one point I used one of those params outside the package, so I moved them all. In any case I think it's not good style to put literals in object constructors?

2018-10-20 11:46 UTC, nolash commented on swarm/pss/api.go
> +		hndlr.caps |= handlerCapRaw
wdym?

2018-10-20 11:47 UTC, nolash commented on swarm/pss/pss.go
> +	topicHandlerCaps map[Topic]byte // caches capabilities of each topic's handlers (see handlerCap* consts in types.go)
yes, and avoid needlessly iterating them every time we get a message if there is no handler for the cap.

2018-10-20 11:50 UTC, nolash commented on swarm/pss/types.go
> +	//raw  bool // if true, will allow raw messages to be handled
this way deregister is faster, because you can just or every one.

2018-10-20 11:53 UTC, nolash commented on swarm/pss/pss.go
> +	var isProx bool
> Now I think you execute a raw handler for a message if there is another handler that allows prox even if that handler does not allow prox.

It's not clear to mean what you mean here, but the condition in `pss.go:380` stops handling of raw message if no raw handlers are registered.

2018-10-20 12:16 UTC, nolash commented on swarm/pss/pss.go
> +func (p *Pss) Register(topic *Topic, hndlr *handler) func() {
But again, doesn't this mean that duplicate topics cannot exist? Apart for the code perhaps being clearer, what benefits do we gain from this? The benefits you list in previous comment all pertain to code structure benefits, not functionality. Or am I mistaken?

As far as the keys go..

> lookup decryption key from hint and open for sym

... I want to refactor out the keys handling into a separate cache object, which also would take care of storing and loading existing keys. That will also make the code nicer.

2018-10-21 07:39 UTC, zelig commented on swarm/pss/pss.go
> +func (p *Pss) Register(topic *Topic, hndlr *handler) func() {
> But again, doesn't this mean that duplicate topics cannot exist?

no it wouldnt, the handler at 'TOPIC+TYPE' has `[]handlerFunc` so there can be several handlers even per topic of the same type. 

> .. I want to refactor out the keys handling into a separate cache object

ok i support that

2018-10-21 07:41 UTC, zelig commented on swarm/pss/pss.go
> +	var isProx bool
sure but it still tries it even though we could know better by then....

2018-10-21 07:42 UTC, zelig commented
@nolash https://travis-ci.org/ethersphere/go-ethereum/jobs/443796697#L508

2018-11-10 06:25 UTC, zelig requested changes
unused var https://travis-ci.org/ethersphere/go-ethereum/jobs/452808218#L503

2018-11-10 10:43 UTC, zelig commented
Also, the algo for forwarding needs fixing as per our convo (see my code)
https://github.com/ethersphere/go-ethereum/blob/11f152819632d3c7a09de5f468e2f506280dd75d/swarm/pss/pss.go#L875

2018-11-10 12:01 UTC, nolash commented
> Also, the algo for forwarding needs fixing as per our convo (see my code)

@zelig yes but since it's unrelated to the feature this PR is introducing I will put it in a separate PR

2018-11-10 12:02 UTC, nolash commented
> so you dont agree it is a better way or just leave it for later?

@zelig what do you mean?

2018-11-10 12:09 UTC, nolash commented on swarm/pss/pss_test.go
> +		kad.MinBinSize + 1,
I wanted to make sure that I have two more peers than NNs, and the NNs in this test will be in two separate bins. Are you arguing that the test will break if `kad.MinBinSize` would change?

I do agree however that the naming in this test makes it confusing. How about I copy the `kad.MinBinSize` to a local var, and only use local var names thereafter?

2018-11-12 17:04 UTC, zelig commented
what is the ETA on this?



>>    so you dont agree it is a better way or just leave it for later?

> @zelig what do you mean?

I mean the rich topic thing i suggested. I think it would be better, but lets leave it for later
please at least fix the above linter issue, thanks

2018-11-12 18:33 UTC, nolash commented
Right, there are a couple of things missing here, I see. I'll try to get it done tomorrow.

Rich topic might be good, but yes separate PR.

2018-11-13 10:02 UTC, nolash commented on swarm/pss/pss.go
> +	if p.isSelfPossibleRecipient(pssmsg, false) && p.topicHandlerCaps[psstopic]&handlerCapProx == 0 {
I believe it is. Nice one!

2018-11-13 10:02 UTC, nolash commented on swarm/pss/pss.go
> +			log.Trace("norawhandler")
That would log `Warn` every time someone sends a raw message to my neighborhood or to everyone that I don't recognize. Isn't that a bit excessive?

2018-11-14 01:38 UTC, zelig approved these changes

2018-11-14 01:40 UTC, zelig commented
could you please fix this https://travis-ci.org/ethersphere/go-ethereum/jobs/454417444#L503?

2018-11-20 08:38 UTC, zelig requested changes
would you take care of the change requests

2018-11-20 08:38 UTC, zelig commented on swarm/network/kademlia.go
> +const (
i thought we agreed to undo this ?

2018-11-20 08:38 UTC, zelig commented on swarm/pss/pss.go
> +func (p *Pss) Register(topic *Topic, hndlr *handler) func() {
so we agreed  on considering this as part of subsequent refactors

2018-11-20 08:38 UTC, zelig commented on swarm/pss/pss.go
> +			log.Trace("norawhandler")
why so? if no handler is registered i should not receive neighbourhood addressed msgs

2018-11-20 08:38 UTC, zelig commented on swarm/pss/types.go
> +func NewHandler(f HandlerFunc) *handler {
ok we leave it for later

2018-11-20 08:38 UTC, zelig commented on swarm/pss/types.go
> +	//raw  bool // if true, will allow raw messages to be handled
pretty please.

2018-11-20 10:10 UTC, nolash commented on swarm/pss/types.go
> +	//raw  bool // if true, will allow raw messages to be handled
I really don't understand why you insist on this. A bitwise `OR` in the register function is clearly the more elegant choice in my opinion.

2018-11-20 10:20 UTC, nolash commented on swarm/network/kademlia.go
> +const (
Sorry I forgot I had changed this both places.

2018-11-20 10:34 UTC, nolash commented on swarm/pss/types.go
> +	//raw  bool // if true, will allow raw messages to be handled
Anyway I've changed it to use bools, even if I do find it uglier and less performant.

2018-11-20 10:55 UTC, nolash commented
@zelig I think this was wrong before. Can you evaluate too please?

https://github.com/ethersphere/go-ethereum/pull/965/files#diff-2d1fd9a8750299d8ae63031e6b30be89R347

2018-11-21 06:02 UTC, zelig requested changes
minor things, otherwise LGTM

2018-11-23 00:43 UTC, zelig requested changes

2018-11-23 00:43 UTC, zelig commented on swarm/pss/pss.go
> +	if po <= depth {
but now the other way round :)

2018-11-23 00:46 UTC, zelig commented
https://travis-ci.org/ethersphere/go-ethereum/jobs/457838997#L506
and tests fail

2018-11-23 08:50 UTC, nolash commented on swarm/pss/pss.go
> +	if po <= depth {
lol sorry

2018-11-23 09:58 UTC, zelig approved these changes

2018-11-23 10:03 UTC, nolash commented
Submitted upstream https://github.com/ethereum/go-ethereum/pull/18169

2018-11-23 10:03 UTC, closed without merging