swarm/storage: Fix garbage collection related index corruption
ethersphere/swarm pull request #976
Opened 2018-10-29 20:36 UTC by nolash

This PR fixes the invalid byte slice passed to the access count incrementer, causing index pointers to persist even though data rows and gc rows persist.

It also introduces a Cleanup method for correcting the damage done to already existing datastores due to the above.

Tasks:

- [x] Fix corrupt data parameter to accesscount updater
- [x] Cleanup method for correcting all entry nodes
- [x] Add test for entry cleanups
- [ ] Count remaining chunks and update entrycount and proximity bin pointers
- [ ] Add test for summary entries
- [ ] Add cleanup to migration

2018-11-04 06:53 UTC, zelig reviewed
@ @

2018-11-04 06:53 UTC, zelig commented on swarm/storage/ldbstore.go
> +// this seems to be unused
lets remove then

2018-11-04 06:53 UTC, zelig commented on swarm/storage/ldbstore.go
> +	// TODO: why is this indexcount and not the count of items in po
because this is a cursor where left off with PULL syncing

2018-11-09 10:06 UTC, nonsense commented on swarm/storage/localstore.go
> -		if schema == "" {
I find this confusing.

We should have an if-block for every type of dbschema that is possible on users machines.

It is possible that a user has not updated their Swarm process and are still on schema == "", it is possible that they are also on schema purity and it is possible that they have updated to halloween - this makes it 3 blocks.

Having nested if checks for this is not ideal.

2018-11-09 10:07 UTC, nonsense commented on swarm/storage/schema.go
> +const DbSchemaHalloween = "halloween"
Please add a comment about this schema, and why/when we are introducing it.

2018-11-09 10:07 UTC, nonsense commented on swarm/storage/schema.go
> +//const CurrentDbSchema = DbSchemaPurity
Remove commented code please.

2018-11-09 10:22 UTC, zelig requested changes

2018-11-09 10:22 UTC, zelig commented on swarm/storage/localstore.go
> +				// fix garbage screwed garbage collection and indices
comment!

2018-11-09 10:22 UTC, zelig commented on swarm/storage/ldbstore_test.go
> +	_, err = ldb.db.Get(dataKey)
this is confusing maybe worth a comment that the first chunk has storageIdx 0 on `dataKey[2:10]`

2018-11-09 10:22 UTC, zelig commented on swarm/storage/ldbstore.go
> +	log.Warn("inserting index value", "v", idata, "index", index)
remove logline

2018-11-09 10:22 UTC, zelig commented on swarm/storage/ldbstore.go
> +
remove newline

2018-11-09 10:22 UTC, zelig commented on swarm/storage/ldbstore.go
> +func (s *LDBStore) CleanIndex() error {
comment function

2018-11-09 14:15 UTC, zelig approved these changes

2018-11-11 15:13 UTC, frncmx commented
PR has been opened to upstream.
https://github.com/ethereum/go-ethereum/pull/18080

2018-11-11 15:13 UTC, closed without merging

2018-11-11 20:59 UTC, nolash commented on swarm/storage/localstore.go
> +		ls.DbStore.CleanGCIndex()
Shouldn't this be `ls.migrateFromPurityToHalloween()`?